README.rst
Project name changed from the Sorna to the Backend.AI
=> Project name changed from the Sorna to the Backend.AI

ai/backend/client/cli/proxy.py, ai/backend/client/request.py
* Update Request to support raw request
* Add Websocket Proxy with aiohttp
=> Add websocket support for proxy cli command

src/ai/backend/client/cli/vfolder.py, src/ai/backend/client/vfolder.py, tests/test_vfolder.py
Pull request for [manager#91](https://github.com/lablup/backend.ai-manager/issues/91).
Added 'host' optional param when creating a new vfolder.
=> General vfolder host

src/ai/backend/client/cli/run.py, src/ai/backend/client/kernel.py
Pull request for [manager#74](https://github.com/lablup/backend.ai-manager/issues/74).
=> Add clean option in run command

src/ai/backend/client/cli/__init__.py, src/ai/backend/client/cli/manager.py, src/ai/backend/client/manager.py, src/ai/backend/client/session.py, tests/test_manager.py
Pull request for [lablup/backend.ai-manager#106](https://github.com/lablup/backend.ai-manager/issues/106).
=> Freeze / unfreeze commands

src/ai/backend/client/cli/run.py, src/ai/backend/client/kernel.py
* Fully streaming execution in CLI
* Terminal access in CLI!
=> Streaming execution

src/ai/backend/client/cli/__init__.py, src/ai/backend/client/cli/app.py
=> Add the app support BETA

src/ai/backend/client/agent.py, src/ai/backend/client/cli/admin/agents.py, src/ai/backend/client/cli/admin/images.py, src/ai/backend/client/cli/admin/sessions.py, src/ai/backend/client/image.py
client cli admin commands
1. admin sessions, admin agents
- added option --all (without option flag, default load length is 10.)
- graphQL pagination for option --all (lazy loading using click.pager and generator)
2. admin alias-image, admin dealias-image, admin rescan-images
- client commands to update etcd images data
=> client cli command - graphQL pagination, added etcd command

src/ai/backend/client/auth.py, src/ai/backend/client/cli/config.py, src/ai/backend/client/config.py, src/ai/backend/client/request.py, src/ai/backend/client/session.py
Let's allow users to login/logout console servers and use the API through them on the CLI interface and the API function SDK.
=> Console server support

src/ai/backend/client/image.py
Add very simple two interfaces.
* Get form meta data for image import
* Build image
=> Image import interface

.gitignore, src/ai/backend/client/cli/app.py, src/ai/backend/client/cli/logs.py, src/ai/backend/client/cli/run.py, src/ai/backend/client/compat.py, src/ai/backend/client/kernel.py
This PR implements service url template fetching. 
Check lablup/backend.ai-agent#152 and lablup/backend.ai#54 for more details.
=> Add support for handing service url template

src/ai/backend/client/cli/vfolder.py, src/ai/backend/client/vfolder.py
This PR implements new unmanaged vFolder API (lablup/backend.ai#74) and `download_with_token`'s token generate API.
=> Implement unmanaged vFolder and download token API

setup.py
[https://github.com/lablup/backend.ai/issues/35](#35)
Entrypoint for unified cli.
@achimnol
=> Added entrypoint and removed unnecessary parts

CHANGELOG.rst, src/ai/backend/client/cli/run.py, src/ai/backend/client/kernel.py
Client counterpart for lablup/backend.ai-manager#250
Internal ticket: OP#225
=> Add support for forced termination

src/ai/backend/client/cli/app.py
In the progress of lablup/backend.ai-agent#189.
=> Refine app proxy support

src/ai/backend/client/cli/pretty.py, src/ai/backend/client/func/session.py
refs lablup/backend.ai-manager#258 (internal ticket #278)
=> Support session UUID prefix queries

changes/111.breaking, src/ai/backend/client/cli/admin/users.py, src/ai/backend/client/func/user.py
Change user's `is_active` field with `status`.
=> refactor: replace user's is_active field into status

src/ai/backend/client/cli/vfolder.py, src/ai/backend/client/func/vfolder.py
Implemented the second functionality listed in issue lablup/backend.ai#150.
=> Add functionality for the user to leave a shared vfolder

changes/154.misc, setup.py
=> setup: Update docs requirements

changes/170.feature, src/ai/backend/client/cli/admin/groups.py, src/ai/backend/client/func/group.py
refs lablup/backend.ai-manager#452
=> feat: Add support for group query by name

changes/171.feature, src/ai/backend/client/cli/admin/agents.py, src/ai/backend/client/cli/admin/keypairs.py, src/ai/backend/client/cli/admin/sessions.py, src/ai/backend/client/cli/admin/storage.py, src/ai/backend/client/cli/admin/users.py, src/ai/backend/client/cli/admin/vfolders.py, src/ai/backend/client/cli/ps.py, src/ai/backend/client/exceptions.py, src/ai/backend/client/func/admin.py, src/ai/backend/client/func/agent.py, src/ai/backend/client/func/keypair.py, src/ai/backend/client/func/session.py, src/ai/backend/client/func/storage.py, src/ai/backend/client/func/user.py, src/ai/backend/client/func/vfolder.py, src/ai/backend/client/pagination.py
refs lablup/backend.ai-manager#449
=> feat: Add queryfilter support

changes/175.misc, setup.py
* Make most of them to set the minimum version, so that other
components that rely on the client SDK could specify more flexible
version ranges.
=> feat: Update dependencies

changes/190.misc, src/ai/backend/client/config.py
* Thanks to @pranavrajpal!
(https://github.com/python/mypy/issues/11853#issuecomment-1002357286)
=> Update mypy to 0.930

changes/192.fix, src/ai/backend/client/cli/ssh.py
* typecheck: "possibly unbound variable" error
=> fix: Regression of "ssh" command

.github/workflows/default.yml, changes/200.feature, changes/200.misc, requirements/lint.txt, requirements/test.txt, requirements/typecheck.txt
Modify following files to add backend.ai-cli module dependency when test push or pull request.
* .github/workflows/default.yml
* requirements/lint.txt
* requirements/test.txt
* requirements/typecheck.txt
=> ci: Install the matching branch of backend.ai-cli

changes/208.feature.md, src/ai/backend/client/cli/pretty.py, src/ai/backend/client/cli/vfolder.py, src/ai/backend/client/func/vfolder.py, tests/test_vfolder.py
refs lablup/backend.ai#385
- fix: Improve error data handling
=> feature: Add vfolder "mv" command

.github/workflows/default.yml, .github/workflows/timeline-check.yml, changes/210.misc.md, requirements/timeline-check.txt
=> setup,ci: Include Python 3.10 in CI

changes/217.feature, src/ai/backend/client/cli/run.py, src/ai/backend/client/cli/session.py, src/ai/backend/client/func/session.py
refs https://github.com/lablup/backend.ai/issues/362
related lablup/backend.ai-manager#567
=> feat: add `callback_url` parameter in session creation API to support session event webhook

changes/222.fix.md, setup.py, src/ai/backend/client/session.py
- setup: Upgrade mypy to 0.950
- fix: Suppress a potential mypy bug (python/mypy#12756)
=> Upgrade mypy to 0.950
