src/ai/backend/client/cli/pretty.py
src/ai/backend/client/cli/run.py

* Extends `backend.ai run` command with new options: `--env-range`, `--build-range`, and `--exec-range` which accept "range expression" and may be specified multiple times.
- Each range expression has a `key=range` structure and `range` part consists of a type prefix like `range:`, `linspace:`, or `case:`. After the type prefix, a comma separated list comes for the arguments to each range generator type.
- The `run` command now generates all combinations of given range expressions and creates multiple sessions corresponding to them.
* When running multiple sessions, the console outputs are logged into a separate log directory (`~/.cache/backend.ai/client-logs` with their client-side session token and indices).
* Parallel execution is only supported in the websocket streaming mode. In the …

CLI support for running experiments with various parameter combinations

---

src/ai/backend/client/__init__.py
src/ai/backend/client/admin.py
src/ai/backend/client/agent.py
src/ai/backend/client/auth.py
src/ai/backend/client/base.py
src/ai/backend/client/cli/__init__.py
src/ai/backend/client/cli/proxy.py
src/ai/backend/client/compat.py
src/ai/backend/client/config.py
src/ai/backend/client/kernel.py
src/ai/backend/client/keypair.py
src/ai/backend/client/request.py
src/ai/backend/client/session.py
src/ai/backend/client/vfolder.py
tests/conftest.py
tests/test_base.py
tests/test_cli_proxy.py
tests/test_integration.py
tests/test_kernel.py
tests/test_request.py
tests/test_vfolder.py

* Use aiohttp's startup/cleanup signals to initialize and destroy the client session.
* Use the client session everywhere for the lifetime of proxy command.
* Adopt API v4's authentication mechanism which do not include the body. (lablup/backend.ai#30)
* Use metaclass to seamlessly wrap async API functions as synchronous versions.

Hotfix and refactoring of proxy

---

setup.py
src/ai/backend/client/cli/__init__.py
src/ai/backend/client/cli/admin/__init__.py
src/ai/backend/client/cli/admin/agents.py
src/ai/backend/client/cli/admin/keypairs.py
src/ai/backend/client/cli/admin/sessions.py
src/ai/backend/client/cli/admin/vfolders.py
src/ai/backend/client/cli/app.py
src/ai/backend/client/cli/config.py
src/ai/backend/client/cli/files.py
src/ai/backend/client/cli/logs.py
src/ai/backend/client/cli/manager.py
src/ai/backend/client/cli/proxy.py
src/ai/backend/client/cli/ps.py
src/ai/backend/client/cli/run.py
src/ai/backend/client/cli/vfolder.py
src/ai/backend/client/request.py

Related to issue #46.
* Click package is adopted to improve development of cli commands.
* Custom parsers and `register_command` was removed.
* Added custom `Group` class to support command alias (which is not supported natively in Click).
* `lcc` and `lpython` commands are still working, but the entry point is separated from the main entry point.

Adapt Click package for cli development

---

setup.py

The backend.ai-client now does not use namedlist.
I think it's better to remove it.

fixing requres (remove namedlist , We don't use namedlist in client)

---

.gitignore
src/ai/backend/client/agent.py
src/ai/backend/client/cli/admin/agents.py
src/ai/backend/client/session.py

Added agent watcher commands.
-  Get agent/watcher status: `backendai admin watcher status`
-  Start agent: `backendai admin watcher start <agent-id>`
-  Stop agent: `backendai admin watcher stop <agent-id>`
-  Restart agent: `backendai admin watcher restart <agent-id>`

Agent watcher support

---

src/ai/backend/client/cli/run.py
src/ai/backend/client/kernel.py

In `resource_opts` option, shared memory size can be specified like `--resource-opts shm-size 1g`.

Add resource_opts option in creating a session

---

.travis.yml

Changing CI configs always involve too many fragmented commits. 😥 
And I figured out that Travis CI does not support Python builds on macOS... 😞
I need to add installation scripts that manually installs Python, but I just don't have enought time for it.
=> This is a good topic for contributon participants! :wink:

Just some 삽질 with Travis CI

---

src/ai/backend/client/cli/admin/sessions.py
src/ai/backend/client/cli/logs.py
src/ai/backend/client/cli/ps.py
src/ai/backend/client/cli/run.py
src/ai/backend/client/kernel.py

This is the client-side counterpart of lablup/backend.ai-manager#199 and lablup/backend.ai#42.
It adds the "result" column and "task ID" column (only displayed with `--show-tid` flag) to the `backend.ai ps` and `backend.ai admin sessions` commands.
It also adds the new `backend.ai task-logs <taskId>` command, which streams the log file directly.
Internally I implemented the `Kernel.get_task_logs()` API function using async generator.

Support batch tasks

---

.gitignore
src/ai/backend/client/cli/run.py
src/ai/backend/client/config.py
src/ai/backend/client/kernel.py

This PR resolves lablup/backend.ai#69 , by implementing Kernel API's  updated `mount_map` property.
What has changed:
- Default API version updated to `v4.20191119`: check PR lablup/backend.ai-manager#155 for details.
- Kernel API implementation updated to handle new `mount_map` property.
- `start`/`run` command now accepts custom vFolder mount location, so user can select where to mount their vFolders.
- vFolders can only be mounted under `/home/work`. If not, Backend.AI Agent will return `RuntimeError`. 
- Setting mount location on dot(.) prefixed vFolders will be ignored by Backend.AI Agent.

mount vFolder on a custom location

---

docs/cli/sessions.rst
src/ai/backend/client/cli/admin/sessions.py
src/ai/backend/client/cli/ps.py

lablup/backend.ai#87
@achimnol 
- Added --format/-f options for "backend.ai ps"/"backend.ai admin session" commands
- Added --plain option to see process status info in plain tabular format

Added --format and --plain options to the 'backend.ai ps' command

---

src/ai/backend/client/cli/admin/__init__.py
src/ai/backend/client/cli/admin/etcd.py
src/ai/backend/client/func/etcd.py
src/ai/backend/client/session.py

* Get a key/value pair:
- `backend.ai admin etcd get <key>`
* Get all key/value pairs prefixed with given key:
- `backend.ai admin etcd get --prefix <key>`
* Set a key/value pair:
- `backend.ai admin etcd set <key> <value>`
* Set a key/value pair with value as a dict:
- `backend.ai admin etcd set <key> '<stringified-json-value>'`
- If value is not json-parsable, single key/value will be set.
* Delete a key/value pair:
- `backend.ai admin etcd delete <key>`
* Delete all key/value pairs prefixed with given key:
- `backend.ai admin etcd delete --prefix <key>`

Add etcd commands for admin

---

src/ai/backend/client/cli/pretty.py

Error detail is carried by `msg` in `exc.data`, not `data`.

fix: server's error detail is not displayed

---

changes/117.feature
src/ai/backend/client/cli/admin/domains.py
src/ai/backend/client/cli/admin/groups.py
src/ai/backend/client/cli/admin/users.py
src/ai/backend/client/func/domain.py
src/ai/backend/client/func/group.py
src/ai/backend/client/func/user.py

This PR adds purge commands to delete users, groups, and domains.
How to use:
```shell
backend.ai admin users purge <email>
backend.ai admin groups purge <group-id>
backend.ai admin domains purge <domain-name>
```
Related Issue: lablup/backend.ai-manager#302
Related: OP#651

feat: purge command for users, groups, and domains

---

changes/119.fix
src/ai/backend/client/func/keypair.py

`user_id` filter is missing in keypair's `paginated_list` query. It exists in `list` query. So, this PR just extends the `paginated_list` query to accept `user_id` parameter.
Related: lablup/backend.ai-manager-hub#49, OP#668.

fix: user_id filter is missing in paginated keypair list

---

changes/122.feature
src/ai/backend/client/cli/admin/keypairs.py

Some customers want to see the user's `full_name` in keypair query. So, This PR supports it.
Related: https://github.com/lablup/backend.ai-manager/pull/313.
Internal ticket: OP#672.

feat: display full_name when querying keypair(s)

---

changes/159.feature
src/ai/backend/client/cli/vfolder.py
src/ai/backend/client/func/vfolder.py

This PR adds commands to share or unshare a group virtual folder to users directly with overriding permission. This is to allow specified users (usually teachers with user account) can upload data/materials to a group virtual folder while it is shared as read-only for other group users (usually students).
How to use:
```console
$ backend.ai vfolder share -p wd my_group_folder user@lablup.com friend@lablup.com
Shared with wd permission to:
- user@lablup.com
- friend@lablup.com
$ backend.ai vfolder unshare my_group_folder user@lablup.com friend@lablup.com
Unshared from:
- user@lablup.com
- friend@lablup.com
```
Related: https://github.com/lablup/backend.ai-manager/pull/419

feat: add command to share/unshare group virtual folders to users

---

changes/172.fix
src/ai/backend/client/func/user.py

* Previously `status` was using a wrong type (`bool`).

fix: Use predefined values for role and status args for CreateUser/ModifyUser mutations

---

changes/180.fix
src/ai/backend/client/cli/admin/scaling_group.py
src/ai/backend/client/cli/params.py
src/ai/backend/client/func/scaling_group.py

This is follow-up to #163.
* Click invokes ParamType.convert() method *twice* for string default values,
which is unfortunately indistinguishable by the type as the official doc says
when the user passes a signle JSON string literal.

fix: Handling default values in JSONParamType

---

changes/189.feature
src/ai/backend/client/cli/session.py
src/ai/backend/client/func/session.py

This PR adds new rename_session API, as described on lablup/backend.ai#296.

feat: Add support for session renaming

---

.github/workflows/default.yml
changes/202.fix

* Append backup file extension on sed command not to make error when tests on macOS.

fix: add backup file suffix not to make error in sed command.

---

changes/204.fix
docs/cli/storage.rst
src/ai/backend/client/cli/run.py
src/ai/backend/client/cli/session.py
src/ai/backend/client/func/session.py

Resolve: lablup/backend.ai#329
User help text is edited about arbitrary path using. Default path and relative path are /home/work, but users can use absolute path when they mount.
Funtions are not changed, because most of mounting functions are in manager/agent.

fix: edit help text about arbitrary vfolder path mounting

---

changes/205.fix
src/ai/backend/client/cli/vfolder.py

resolved : https://github.com/lablup/backend.ai/issues/354
**prevent blocking of the whole manager while cloning a vfolder**
- **Run the clone operation as a background task and just return the bgtask ID in the vfolder clone API, so that clients could keep track of the progress and result.**
- **Split the destination vfolder creation and actual clone operations, and insert the database transaction to create the destination vfolder record between them.**

feat: Use bgtask API to track progress of vfolder clone asynchronously

---

changes/209.feature.md
src/ai/backend/client/cli/pretty.py

Instead of two-word "Error details", use more sensible field names "Message" and "Data".
The message field is a human-readable string of the error description while the data field contains machine-readable additional information if available.

feat: Improve CLI error message format

---

changes/215.fix.md
src/ai/backend/client/cli/admin/keypair.py
src/ai/backend/client/output/fields.py
src/ai/backend/client/output/types.py

In line with lablup/backend.ai#365

fix: Deprecate concurrency_limit (replaced with max_concurrent_sessions)

---

changes/216.fix
src/ai/backend/client/func/group.py

There is no such field `uuid` in manager's `groups` model. This raises `'Cannot query field "uuid" on type "Group". Did you mean "id"?'` error when creating a group (project) when `fields` parameter is not specified.

fix: remove invalid "uuid" field from groups model

---

changes/218.fix
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/client/func/vfolder.py

Since vfolder_list resolver method does not support access key field, remove access_key option in `admin vfolder list` command.
1. No access_key parameter at resolver method. https://github.com/lablup/backend.ai-manager/blob/main/src/ai/backend/manager/models/gql.py#L1073-#L1104
2. Manager already filters query by user email.  https://github.com/lablup/backend.ai-manager/blob/main/src/ai/backend/manager/api/vfolder.py#L426

fix: remove access key option in vfolder list

---

changes/220.fix
src/ai/backend/client/compat.py

remove the deprecated argument loop at asyncio.gather since the loop parameter has been removed from Python 3.10 https://docs.python.org/ko/3/library/asyncio-task.html#asyncio.gather

fix: remove deprecated arg at asyncio.gather
